### ISSUE TITLE
SentencePieceExtractor extract argument error

### ISSUE THREAD

**Issue by mapleque** [InternLM/InternLM-Math#3]
The following error on demo running:

```
Traceback (most recent call last):
  File "7b.py", line 3, in <module>
    tokenizer = AutoTokenizer.from_pretrained("internlm/internlm2-math-7b", trust_remote_code=True)
  File "/home/xx/.local/lib/python3.6/site-packages/transformers/models/auto/tokenization_auto.py", line 528, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/xx/.local/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1787, in from_pretrained
    **kwargs,
  File "/home/xx/.local/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1915, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/xx/.cache/huggingface/modules/transformers_modules/internlm/internlm2-math-7b/22fcfb01a3a03b6ba5e692159a37914fb70591cd/tokenization_internlm2_fast.py", line 142, in __init__
    **kwargs,
  File "/home/xx/.local/lib/python3.6/site-packages/transformers/tokenization_utils_fast.py", line 112, in __init__
    fast_tokenizer = convert_slow_tokenizer(slow_tokenizer)
  File "/home/xx/.local/lib/python3.6/site-packages/transformers/convert_slow_tokenizer.py", line 1033, in convert_slow_tokenizer
    return converter_class(transformer_tokenizer).converted()
  File "/home/xx/.local/lib/python3.6/site-packages/transformers/convert_slow_tokenizer.py", line 479, in converted
    tokenizer = self.tokenizer(self.proto)
  File "/home/xx/.cache/huggingface/modules/transformers_modules/internlm/internlm2-math-7b/22fcfb01a3a03b6ba5e692159a37914fb70591cd/tokenization_internlm2_fast.py", line 81, in tokenizer
    _, merges = SentencePieceExtractor(self.original_tokenizer.vocab_file).extract(vocab_scores)
TypeError: extract() takes 1 positional argument but 2 were given
```

How can deal with it?

**Comment by yinghy18** [comment]
What is your environment? Especially your transformer version.

**Comment by mapleque** [comment]
> What is your environment? Especially your transformer version.

torch 1.10.1+cu102
transformers 4.18.0

Or which version should I take?

**Comment by yinghy18** [comment]
Your transformers are too low, maybe upgrade to the latest version

**Comment by mapleque** [comment]
OK，I'll try, thank you.
